........EEEEE.EE
======================================================================
ERROR: test_list_int (__main__.Test09_mathematics_geometry_whoami_getname.test_list_int)
*** Test02 **** GIVEN: import mathematics.geometry.whoami as whoami *** FUNCTION CALL: whoami.getname() *** EXPECT: 'mathematics.geometry.whoami' ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eli-thomas/Documents/CPSC223P/CPSC223P-Lab5/test.py", line 84, in test_list_int
    self.assertEqual('mathematics.geometry.whoami', whoami.getname())
                                                    ^^^^^^^^^^^^^^
AttributeError: module 'mathematics.geometry.whoami' has no attribute 'getname'

======================================================================
ERROR: test_list_int (__main__.Test10_mathematics_geometry_rectangle_perimeter.test_list_int)
*** Test10 **** GIVEN: import mathematics.geometry.rectangle as rectangle *** FUNCTION CALL: rectangle.perimeter(length = 3, width = 7) *** EXPECT: 20 ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eli-thomas/Documents/CPSC223P/CPSC223P-Lab5/test.py", line 93, in test_list_int
    self.assertEqual(20, rectangle.perimeter(length = 3, width = 7))
                         ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'mathematics.geometry.rectangle' has no attribute 'perimeter'

======================================================================
ERROR: test_list_int (__main__.Test11_mathematics_geometry_rectangle_area.test_list_int)
*** Test11 **** GIVEN: import mathematics.geometry.rectangle as rectangle *** FUNCTION CALL: rectangle.area(length = 3, width = 7) *** EXPECT: 21 ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eli-thomas/Documents/CPSC223P/CPSC223P-Lab5/test.py", line 102, in test_list_int
    self.assertEqual(21, rectangle.area(length = 3, width = 7))
                         ^^^^^^^^^^^^^^
AttributeError: module 'mathematics.geometry.rectangle' has no attribute 'area'

======================================================================
ERROR: test_list_int (__main__.Test12_mathematics_geometry_cube_surfacearea.test_list_int)
*** Test12 **** GIVEN: import mathematics.geometry.cube as cube *** FUNCTION CALL: cube.surface_area(side=5) *** EXPECT: 150 ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eli-thomas/Documents/CPSC223P/CPSC223P-Lab5/test.py", line 111, in test_list_int
    self.assertEqual(150, cube.surface_area(side=5))
                          ^^^^^^^^^^^^^^^^^
AttributeError: module 'mathematics.geometry.cube' has no attribute 'surface_area'

======================================================================
ERROR: test_list_int (__main__.Test13_mathematics_geometry_cube_volume.test_list_int)
*** Test13 **** GIVEN: import mathematics.geometry.cube as cube *** FUNCTION CALL: cube.volume(side=5) *** EXPECT: 125 ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eli-thomas/Documents/CPSC223P/CPSC223P-Lab5/test.py", line 120, in test_list_int
    self.assertEqual(125, cube.volume(side=5))
                          ^^^^^^^^^^^
AttributeError: module 'mathematics.geometry.cube' has no attribute 'volume'

======================================================================
ERROR: test_list_int (__main__.Test15_mathematics_numbers_init.test_list_int)
*** Test15 **** GIVEN: import mathematics.numbers.__init__ as init *** FUNCTION CALL: init.__all__ *** EXPECT: ['whoami', 'series'] ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eli-thomas/Documents/CPSC223P/CPSC223P-Lab5/test.py", line 137, in test_list_int
    import mathematics.numbers.__init__ as init
ModuleNotFoundError: No module named 'mathematics.numbers.__init__'

======================================================================
ERROR: test_list_int (__main__.Test16_mathematics_geometry_init.test_list_int)
*** Test16 **** GIVEN: import mathematics.geometry.__init__ as init *** FUNCTION CALL: init.__all__ *** EXPECT: ['whoami', 'circle', 'cube'] ***
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eli-thomas/Documents/CPSC223P/CPSC223P-Lab5/test.py", line 146, in test_list_int
    import mathematics.geometry.__init__ as init
ModuleNotFoundError: No module named 'mathematics.geometry.__init__'

----------------------------------------------------------------------
Ran 16 tests in 0.007s

FAILED (errors=7)
